apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm
spec:
  template:
    metadata:
      labels:
        intent: multiarch
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: capacity-spread
          operator: In
          values:
            - "1"
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
